import { useState } from 'react'
import JSZip from 'jszip'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism'
import { Copy, Download, FileCode } from 'lucide-react'
import { SAMPLE_ASSETS } from '../../../app/mock/sampleProject'
import { useApp } from '../../../app/AppContext'

interface Props {
  onDownload?: () => void
}

interface CodeFile {
  name: string
  language: string
  content: string
}

const FILES: CodeFile[] = [
  {
    name: 'model.py',
    language: 'python',
    content: `"""
Transformer Model Implementation
Based on: Attention Is All You Need (Vaswani et al., 2017)
Generated by Monjez AI - Production Ready
"""
import math
import torch
import torch.nn as nn
import torch.nn.functional as F


class PositionalEncoding(nn.Module):
    """Sinusoidal positional encoding (Section 3.5)."""

    def __init__(self, d_model: int, max_len: int = 5000):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(
            torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model)
        )
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer("pe", pe.unsqueeze(0))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x + self.pe[:, : x.size(1)]


class MultiHeadAttention(nn.Module):
    """Scaled dot-product multi-head attention (Section 3.2.2)."""

    def __init__(self, d_model: int, n_heads: int, dropout: float = 0.1):
        super().__init__()
        assert d_model % n_heads == 0, "d_model must be divisible by n_heads"
        self.d_k = d_model // n_heads
        self.n_heads = n_heads
        self.W_q = nn.Linear(d_model, d_model)
        self.W_k = nn.Linear(d_model, d_model)
        self.W_v = nn.Linear(d_model, d_model)
        self.W_o = nn.Linear(d_model, d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, q, k, v, mask=None):
        B = q.size(0)
        # Project & split into heads: (B, n_heads, seq_len, d_k)
        Q = self.W_q(q).view(B, -1, self.n_heads, self.d_k).transpose(1, 2)
        K = self.W_k(k).view(B, -1, self.n_heads, self.d_k).transpose(1, 2)
        V = self.W_v(v).view(B, -1, self.n_heads, self.d_k).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_k)
        if mask is not None:
            scores = scores.masked_fill(mask == 0, -1e9)
        attn = F.softmax(scores, dim=-1)
        attn = self.dropout(attn)
        out = torch.matmul(attn, V)

        out = out.transpose(1, 2).contiguous().view(B, -1, self.n_heads * self.d_k)
        return self.W_o(out)


class FeedForward(nn.Module):
    """Position-wise feed-forward (Section 3.3)."""

    def __init__(self, d_model: int, d_ff: int = 2048, dropout: float = 0.1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(d_ff, d_model),
        )

    def forward(self, x):
        return self.net(x)


class EncoderLayer(nn.Module):
    def __init__(self, d_model, n_heads, d_ff, dropout=0.1):
        super().__init__()
        self.attn = MultiHeadAttention(d_model, n_heads, dropout)
        self.ff = FeedForward(d_model, d_ff, dropout)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        # Pre-norm variant for stability
        x = x + self.dropout(self.attn(self.norm1(x), self.norm1(x), self.norm1(x), mask))
        x = x + self.dropout(self.ff(self.norm2(x)))
        return x


class Transformer(nn.Module):
    """Encoder-only Transformer for sequence classification."""

    def __init__(
        self,
        vocab_size: int,
        d_model: int = 512,
        n_heads: int = 8,
        n_layers: int = 6,
        d_ff: int = 2048,
        max_len: int = 512,
        dropout: float = 0.1,
        n_classes: int = 2,
    ):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, d_model)
        self.pos = PositionalEncoding(d_model, max_len)
        self.layers = nn.ModuleList([
            EncoderLayer(d_model, n_heads, d_ff, dropout) for _ in range(n_layers)
        ])
        self.norm = nn.LayerNorm(d_model)
        self.head = nn.Linear(d_model, n_classes)

    def forward(self, x, mask=None):
        x = self.embed(x) * math.sqrt(self.embed.embedding_dim)
        x = self.pos(x)
        for layer in self.layers:
            x = layer(x, mask)
        x = self.norm(x)
        x = x.mean(dim=1)        # mean-pool over sequence
        return self.head(x)
`,
  },
  {
    name: 'dataset.py',
    language: 'python',
    content: `"""
Dataset loader using HuggingFace datasets + a simple BPE tokenizer.
Loads IMDB sentiment data out-of-the-box for end-to-end training.
"""
import torch
from torch.utils.data import Dataset, DataLoader
from datasets import load_dataset
from transformers import AutoTokenizer


class TextClassificationDataset(Dataset):
    """Wraps HuggingFace datasets into a PyTorch Dataset."""

    def __init__(self, hf_split, tokenizer, max_len: int = 256):
        self.data = hf_split
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self) -> int:
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data[idx]
        enc = self.tokenizer(
            row["text"],
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "label": torch.tensor(row["label"], dtype=torch.long),
        }


def get_loaders(batch_size: int = 32, max_len: int = 256):
    """Returns train/test DataLoaders for IMDB sentiment classification."""
    # Loads from HF datasets cache (downloads on first run, ~84MB)
    raw = load_dataset("imdb")
    tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

    train_ds = TextClassificationDataset(raw["train"], tokenizer, max_len)
    test_ds = TextClassificationDataset(raw["test"], tokenizer, max_len)

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, num_workers=2)

    return train_loader, test_loader, tokenizer.vocab_size


if __name__ == "__main__":
    train_loader, test_loader, vocab = get_loaders(batch_size=4)
    batch = next(iter(train_loader))
    print(f"vocab_size={vocab}")
    print(f"input_ids shape: {batch['input_ids'].shape}")
    print(f"label sample: {batch['label'][:4].tolist()}")
`,
  },
  {
    name: 'train.py',
    language: 'python',
    content: `"""
End-to-end training script.
- Loads IMDB sentiment data via dataset.py
- Trains the Transformer with Adam + warmup schedule (per the paper)
- Validates each epoch and saves the best checkpoint
"""
import os
import torch
import torch.nn as nn
from tqdm import tqdm

from model import Transformer
from dataset import get_loaders


def lr_lambda(step: int, d_model: int = 512, warmup: int = 4000) -> float:
    """Section 5.3: lrate = d_model^-0.5 * min(step^-0.5, step * warmup^-1.5)."""
    step = max(step, 1)
    return (d_model ** -0.5) * min(step ** -0.5, step * warmup ** -1.5)


def evaluate(model, loader, device) -> float:
    """Returns accuracy on the given loader."""
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for batch in loader:
            ids = batch["input_ids"].to(device)
            labels = batch["label"].to(device)
            logits = model(ids)
            preds = logits.argmax(dim=-1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    return correct / total if total else 0.0


def train(epochs: int = 3, batch_size: int = 32, lr: float = 1e-4, ckpt_dir: str = "checkpoints"):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {device}")

    # 1) Data
    train_loader, val_loader, vocab_size = get_loaders(batch_size=batch_size)

    # 2) Model
    model = Transformer(vocab_size=vocab_size, n_classes=2).to(device)
    optim = torch.optim.Adam(model.parameters(), lr=lr, betas=(0.9, 0.98), eps=1e-9)
    scheduler = torch.optim.lr_scheduler.LambdaLR(optim, lr_lambda=lambda s: lr_lambda(s))
    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

    # 3) Training loop
    os.makedirs(ckpt_dir, exist_ok=True)
    best_acc = 0.0
    step = 0

    for epoch in range(1, epochs + 1):
        model.train()
        running_loss = 0.0
        pbar = tqdm(train_loader, desc=f"Epoch {epoch}/{epochs}")
        for batch in pbar:
            ids = batch["input_ids"].to(device)
            labels = batch["label"].to(device)

            logits = model(ids)
            loss = criterion(logits, labels)

            optim.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optim.step()
            scheduler.step()

            running_loss += loss.item()
            step += 1
            pbar.set_postfix(loss=f"{running_loss/(pbar.n+1):.4f}")

        val_acc = evaluate(model, val_loader, device)
        print(f"Epoch {epoch}: val_acc = {val_acc*100:.2f}%")

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), os.path.join(ckpt_dir, "best.pt"))
            print(f"✓ Saved new best ({best_acc*100:.2f}%)")

    print(f"\\nDone. Best val accuracy: {best_acc*100:.2f}%")
    return best_acc


if __name__ == "__main__":
    train(epochs=3, batch_size=32)
`,
  },
  {
    name: 'evaluate.py',
    language: 'python',
    content: `"""
Standalone evaluation / inference script.
- Loads the saved checkpoint
- Reports accuracy on the test split
- Provides a single-sentence inference helper
"""
import torch
from transformers import AutoTokenizer

from model import Transformer
from dataset import get_loaders


def load_model(ckpt: str = "checkpoints/best.pt", device: str = "cpu") -> Transformer:
    _, _, vocab_size = get_loaders(batch_size=1)
    model = Transformer(vocab_size=vocab_size, n_classes=2).to(device)
    state = torch.load(ckpt, map_location=device)
    model.load_state_dict(state)
    model.eval()
    return model


def evaluate_test(ckpt: str = "checkpoints/best.pt") -> float:
    device = "cuda" if torch.cuda.is_available() else "cpu"
    _, test_loader, _ = get_loaders(batch_size=64)
    model = load_model(ckpt, device)

    correct, total = 0, 0
    with torch.no_grad():
        for batch in test_loader:
            ids = batch["input_ids"].to(device)
            labels = batch["label"].to(device)
            preds = model(ids).argmax(dim=-1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    acc = correct / total
    print(f"Test accuracy: {acc*100:.2f}% ({correct}/{total})")
    return acc


def predict_sentiment(text: str, ckpt: str = "checkpoints/best.pt") -> dict:
    """Predict sentiment for a single sentence."""
    device = "cuda" if torch.cuda.is_available() else "cpu"
    tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
    model = load_model(ckpt, device)

    enc = tokenizer(text, return_tensors="pt", padding="max_length", truncation=True, max_length=256)
    ids = enc["input_ids"].to(device)

    with torch.no_grad():
        probs = torch.softmax(model(ids), dim=-1).squeeze(0)

    label = "positive" if probs[1] > probs[0] else "negative"
    return {"text": text, "label": label, "confidence": float(max(probs))}


if __name__ == "__main__":
    print("=" * 50)
    print("Test set evaluation")
    print("=" * 50)
    evaluate_test()

    print("\\n" + "=" * 50)
    print("Single-sentence inference demo")
    print("=" * 50)
    samples = [
        "This movie is absolutely fantastic, I loved every minute!",
        "Worst film I have ever seen. Complete waste of time.",
        "It was okay, nothing special.",
    ]
    for s in samples:
        out = predict_sentiment(s)
        print(f"[{out['label']:8}] ({out['confidence']:.2f}) {out['text']}")
`,
  },
  {
    name: 'requirements.txt',
    language: 'text',
    content: `# Generated by Monjez AI
torch>=2.0.0
datasets>=2.14.0
transformers>=4.35.0
tqdm>=4.65.0
`,
  },
  {
    name: 'README.md',
    language: 'markdown',
    content: `# Transformer Implementation — Generated by Monjez AI

تطبيق كامل لمعمارية Transformer من ورقة *"Attention Is All You Need"* (Vaswani et al., 2017).
هذا المشروع جاهز للتشغيل من الصفر — يقرأ بيانات IMDB من HuggingFace ويدرّب نموذج تصنيف نهاية إلى نهاية.

## محتويات المشروع
| الملف | الوصف |
|---|---|
| \`model.py\` | Transformer + MultiHeadAttention + PositionalEncoding |
| \`dataset.py\` | DataLoader يقرأ IMDB من HuggingFace + tokenizer |
| \`train.py\` | حلقة تدريب كاملة مع warmup + validation |
| \`evaluate.py\` | تقييم على مجموعة الاختبار + استدلال على جملة |
| \`requirements.txt\` | جميع المكتبات المطلوبة |

## التشغيل السريع

\`\`\`bash
# 1. تثبيت المكتبات
pip install -r requirements.txt

# 2. تشغيل التدريب (يحمّل بيانات IMDB في أول مرة)
python train.py

# 3. تقييم النموذج المدرّب
python evaluate.py
\`\`\`

## النتائج المتوقعة
- **Test accuracy:** ~85-88% بعد 3 epochs
- **Training time:** ~12 دقيقة على GPU (NVIDIA T4 أو أعلى)
- **Memory:** ~4GB GPU memory

## معمارية النموذج
- 6 طبقات Encoder
- 8 رؤوس انتباه
- d_model = 512 · d_ff = 2048
- Sinusoidal Positional Encoding
- Pre-norm variant + Residual connections
- Adam optimizer مع warmup (4000 step)
- Label smoothing 0.1

## التخصيص
كل المعاملات في \`train.py\` و \`model.py\` قابلة للتعديل بسهولة:
\`\`\`python
model = Transformer(
    vocab_size=30522,
    d_model=512,
    n_heads=8,
    n_layers=6,
    n_classes=2,
)
\`\`\`

---

🤖 **Generated by [Monjez](https://monjez.app)** — تحويل الأبحاث إلى كود قابل للتشغيل.
`,
  },
]

export default function CodeOutput({ onDownload: _onDownload }: Props) {
  const { toast } = useApp()
  const asset = SAMPLE_ASSETS.code
  const [active, setActive] = useState(0)
  const current = FILES[active]

  function copy() {
    navigator.clipboard.writeText(current.content).then(() =>
      toast({ type: 'success', title: `تم نسخ ${current.name}` })
    )
  }

  async function downloadZip() {
    const zip = new JSZip()
    FILES.forEach((f) => zip.file(f.name, f.content))
    const blob = await zip.generateAsync({ type: 'blob' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = asset.fileName
    a.click()
    URL.revokeObjectURL(url)
    toast({ type: 'success', title: 'تم تنزيل code.zip', description: `${FILES.length} ملفات جاهزة` })
  }

  const lineCount = current.content.split('\n').length

  return (
    <div>
      {/* Action bar */}
      <div className="flex items-center justify-between gap-3 mb-3 flex-wrap">
        <div className="min-w-0">
          <h3 className="text-base font-bold text-white">{asset.label}</h3>
          <p className="text-xs text-white/55 mt-0.5">{asset.description} · {FILES.length} ملفات</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={copy}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 hover:bg-white/10 text-white/75 hover:text-white text-xs font-medium transition-colors"
          >
            <Copy className="w-3.5 h-3.5" />
            نسخ {current.name}
          </button>
          <button
            onClick={downloadZip}
            className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-gradient-to-br from-mint-400 to-mint-600 text-ink-950 text-xs font-bold hover:shadow-mint-glow transition-all"
          >
            <Download className="w-3.5 h-3.5" />
            تحميل {asset.fileName}
          </button>
        </div>
      </div>

      {/* Code window */}
      <div className="rounded-2xl overflow-hidden border border-white/10 bg-[#1e1e1e]">
        <div className="bg-[#252526] border-b border-white/5">
          <div className="flex items-center justify-between px-4 py-2">
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full bg-rose-500/60" />
              <div className="w-3 h-3 rounded-full bg-amber-500/60" />
              <div className="w-3 h-3 rounded-full bg-emerald-500/60" />
            </div>
            <span className="text-[10px] font-mono text-white/40">monjez-transformer-code</span>
            <span className="w-12" />
          </div>
          <div className="flex items-end overflow-x-auto" dir="ltr">
            {FILES.map((f, i) => (
              <button
                key={f.name}
                onClick={() => setActive(i)}
                className={`shrink-0 inline-flex items-center gap-2 px-3.5 py-2 text-xs font-mono transition-colors border-l border-white/5 ${
                  i === active
                    ? 'bg-[#1e1e1e] text-white border-t-2 border-t-mint-400 -mb-px'
                    : 'text-white/45 hover:text-white/80 hover:bg-white/[0.03]'
                }`}
              >
                <FileCode className={`w-3.5 h-3.5 ${i === active ? 'text-mint-400' : ''}`} />
                {f.name}
              </button>
            ))}
          </div>
        </div>

        <div className="max-h-[460px] overflow-auto" dir="ltr">
          <SyntaxHighlighter
            language={current.language === 'text' ? 'plaintext' : current.language}
            style={vscDarkPlus}
            showLineNumbers
            customStyle={{
              margin: 0,
              padding: '20px',
              background: 'transparent',
              fontSize: '12px',
              lineHeight: '1.65',
            }}
            codeTagProps={{ style: { fontFamily: '"JetBrains Mono", monospace' } }}
          >
            {current.content}
          </SyntaxHighlighter>
        </div>

        <div className="flex items-center justify-between px-4 py-2 bg-[#007acc]/15 border-t border-white/5 text-[10px] text-white/55 font-mono">
          <div className="flex items-center gap-3">
            <span>{current.language}</span>
            <span>·</span>
            <span>UTF-8</span>
            <span>·</span>
            <span>LF</span>
          </div>
          <div className="flex items-center gap-3">
            <span>{lineCount} سطر</span>
            <span>·</span>
            <span>{current.content.length} حرف</span>
          </div>
        </div>
      </div>
    </div>
  )
}
